{% set name = "surfinBH" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03d074526c6236a4da2bf510f067a0eb39a4389224e8e0c5e07650a5debbe515

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - setuptools
    - python >=3.6
  run:
    - gwsurrogate
    - h5py
    - lalsuite >=6.70
    - numpy
    - python >=3.6
    - scikit-learn >=0.19.1
    - scipy

test:
  imports:
    - surfinBH
    - surfinBH._eval_pysur
    - surfinBH._fit_evaluators

about:
  home: https://github.com/vijayvarma392/surfinBH
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Surrogate Final BH properties.
  description: |
    surfinBH provides surrogate final Black Hole properties for mergers of binary black holes (BBH).
    These fits are described in the following papers:
      [1] V. Varma, D. Gerosa, L. C. Stein, F. Hébert and H. Zhang, arxiv:1809.09125.
      [2] V. Varma, S. E. Field, M. A. Scheel, J. Blackman, D. Gerosa, L. C. Stein, L. E. Kidder, H. P. Pfeiffer, arxiv:1905.09300.
      [3] M. Boschini, D. Gerosa, V. Varma, et al., arXiv:2307.03435
      [4] L. Magaña Zertuche, L. C. Stein, et al., arXiv:2408.05300
    If you find this package useful in your work, please cite reference [1] and, if available, the relevant paper describing the particular model. Please also cite this package, see the DOI badge at the top of this page for BibTeX keys.
  dev_url: https://github.com/vijayvarma392/surfinBH

extra:
  recipe-maintainers:
    - duetosymmetry
    - vijayvarma392
